language: objective-c
osx_image: xcode11.3
xcode_workspace: TextInputKit.xcworkspace
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - IOS_SDK=iphonesimulator
  - MACOS_SDK=macosx
  - IOS_FRAMEWORK_SCHEME="TextInputKit-iOS"
  - MACOS_FRAMEWORK_SCHEME="TextInputKit-macOS"
  - IOS_EXAMPLE_SCHEME="Example-iOS"
  - MACOS_EXAMPLE_SCHEME="Example-macOS"
  matrix:
    - DESTINATION="OS=13.3,name=iPhone 11 Pro Max"  SDK="$IOS_SDK"    FRAMEWORK_SCHEME="$IOS_FRAMEWORK_SCHEME"    FRAMEWORK_RUN_TESTS="YES" EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME"
    - DESTINATION="OS=12.4,name=iPhone XS Max"      SDK="$IOS_SDK"    FRAMEWORK_SCHEME="$IOS_FRAMEWORK_SCHEME"    FRAMEWORK_RUN_TESTS="YES" EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME"
    - DESTINATION="OS=11.4,name=iPhone 8 Plus"      SDK="$IOS_SDK"    FRAMEWORK_SCHEME="$IOS_FRAMEWORK_SCHEME"    FRAMEWORK_RUN_TESTS="YES" EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME"
    - DESTINATION="OS=10.3.1,name=iPhone 7"         SDK="$IOS_SDK"    FRAMEWORK_SCHEME="$IOS_FRAMEWORK_SCHEME"    FRAMEWORK_RUN_TESTS="YES" EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME"

    - DESTINATION="arch=x86_64"                     SDK="$MACOS_SDK"  FRAMEWORK_SCHEME="$MACOS_FRAMEWORK_SCHEME"  FRAMEWORK_RUN_TESTS="YES" EXAMPLE_SCHEME="$MACOS_EXAMPLE_SCHEME"
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  - carthage bootstrap
script:
  - scripts/travis_script.sh
