language: objective-c
osx_image: xcode8.2
xcode_workspace: TextInputKit.xcworkspace
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - IOS_SDK=iphonesimulator
  - MACOS_SDK=macosx
  - IOS_FRAMEWORK_SCHEME="TextInputKit-iOS"
  - MACOS_FRAMEWORK_SCHEME="TextInputKit-macOS"
  - IOS_EXAMPLE_SCHEME="Example-iOS"
  - MACOS_EXAMPLE_SCHEME="Example-macOS"
  matrix:
    - DESTINATION="OS=10.1,name=iPhone 7"   SDK="$IOS_SDK"    FRAMEWORK_SCHEME="$IOS_FRAMEWORK_SCHEME"    FRAMEWORK_RUN_TESTS="YES" EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME"
    - DESTINATION="OS=9.0,name=iPhone 6"    SDK="$IOS_SDK"    FRAMEWORK_SCHEME="$IOS_FRAMEWORK_SCHEME"    FRAMEWORK_RUN_TESTS="YES" EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME"
    - DESTINATION="OS=8.1,name=iPhone 4S"   SDK="$IOS_SDK"    FRAMEWORK_SCHEME="$IOS_FRAMEWORK_SCHEME"    FRAMEWORK_RUN_TESTS="YES" EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME"

    - DESTINATION="arch=x86_64"             SDK="$MACOS_SDK"  FRAMEWORK_SCHEME="$MACOS_FRAMEWORK_SCHEME"  FRAMEWORK_RUN_TESTS="YES" EXAMPLE_SCHEME="$MACOS_EXAMPLE_SCHEME"
script:
  - scripts/travis_script.sh
